ci: test new command for start

diff --git a/.github/workflows/test:smoke.yml b/.github/workflows/test:smoke.yml
--- a/.github/workflows/test:smoke.yml
+++ b/.github/workflows/test:smoke.yml
@@ -27,7 +27,10 @@ jobs:
         run: node dist/main --help
 
       - name: Smoke start command
-        run: (node dist/main start -v | tee >(grep -q "🔥 Everything is done! 🔥" && pkill -P $$); [ $? -eq 143 ])
+        # run: (node dist/main start -v | tee >(grep -q "🔥 Everything is done! 🔥" && pkill -P $$); [ $? -eq 143 ])
+        # run: (node dist/main start -v & echo $!; tail -f /dev/null & wait $! | grep -q "Starting Topos-Playground..." && pkill -P $(jobs -p) && echo "Success" || echo "Error") 2>/dev/null
+        # run: (node dist/main start & echo $! && node dist/main start | grep -q "Start Topos-Playground..." && pkill -P $(echo $!) && wait $(echo $!) && echo "String found and process killed") || echo "String not found"
+        run: (node dist/main start 2>&1 | tee logfile & echo $! > pidfile ; tail -f logfile | grep -q "🔥 Everything is done! 🔥" && kill $(<pidfile))
 
       - name: Smoke clean command
         run: node dist/main clean -v
